on: push
name: Main workflow
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ '3.6', '3.7', '3.8' ]
    name: Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - uses: dschep/install-poetry-action@v1.2
      - run: poetry install
      - run: poetry run pytest --cov=resubname --cov-report xml --cov-report term-missing
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
